### ISSUE TITLE
problems with graceful-fs

### ISSUE THREAD

**Issue by noamokman** [tschaub/mock-fs#171]
Hi,

It seems that the following code doesn't work:

``` js
mock({
  stuff: 'lol'
});

const fs = require('graceful-fs');

const readStream = fs.createReadStream('stuff');

readStream.pipe(process.stdout);
```

The object `readStream` is empty.
So there is the error: `TypeError: readStream.pipe is not a function`

Whereas, this works:

``` js
mock({
  stuff: 'lol'
});

const fs = require('fs');

const readStream = fs.createReadStream('stuff');

readStream.pipe(process.stdout);
```

Using the latest version of graceful-fs (4.1.9).
node version: v6.8.0

Thanks!

**Comment by blond** [comment]
very similar to #176

**Comment by tschaub** [comment]
This script works with `graceful-fs@4.1.11` and `mock-fs@4.0.0`:

```js
const fs = require('graceful-fs');

mock({
  stuff: 'lol'
});

const readStream = fs.createReadStream('stuff');

readStream.pipe(process.stdout);
```

Note that `require('graceful-fs')` is called before the filesystem is mocked.  Lazy `require()` calls do not after `mock()` calls.
