### PR TITLE
Update fs.stat(), fs.lstat(), and fs.fstat() for Node 7.7+ (fixes #197)

### LINKED ISSUE #197: Calling fs.statSync with an active mock causes an error in Node 7.7.1
Using `mock-fs@4.1.0`, Node 7.7.1

```js
const mockFs = require('mock-fs');

mockFs({});

fs.statSync('foo')
```

This returns stats as expected, but then throws an error on the next tick.

```
Stats { ... }

> TypeError: callback is not a function
    at path/to/mock-fs/lib/binding.js:37:9
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

This is probably caused by https://github.com/nodejs/node/pull/11522.

### PR DESCRIPTION
**Pull request by not-an-aardvark**
Node 7.7 changed the behavior of the `binding.{stat,lstat,fstat}` functions (see https://github.com/nodejs/node/pull/11522). This updates the binding functions used in mock-fs to match the new Node binding behavior, while still maintaining compatibility with old Node versions. The new behavior is detected when the second argument to `binding.{stat,lstat,fstat}` is a `Float64Array`, which would be an invalid argument for previous versions of the binding.

This commit does not add any tests because the existing tests were already broken by the Node update. Given that they're passing now, I think the behavior is already covered, but let me know if there are any tests I should add.

### CODE REVIEW

**Comment by tschaub** [comment]
Thanks for the fix @not-an-aardvark!
