### ISSUE TITLE
Calling fs.statSync with an active mock causes an error in Node 7.7.1

### ISSUE THREAD

**Issue by not-an-aardvark** [tschaub/mock-fs#197]
Using `mock-fs@4.1.0`, Node 7.7.1

```js
const mockFs = require('mock-fs');

mockFs({});

fs.statSync('foo')
```

This returns stats as expected, but then throws an error on the next tick.

```
Stats { ... }

> TypeError: callback is not a function
    at path/to/mock-fs/lib/binding.js:37:9
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

This is probably caused by https://github.com/nodejs/node/pull/11522.

**Comment by straker** [comment]
+1. Doesn't happen with just fs.statSync but also calling `restore`.

```js
const mockFs = require('mock-fs');
mockFs({});

mockFs.restore();
```

**Comment by not-an-aardvark** [comment]
I made a PR to fix this in #198.

**Comment by straker** [comment]
That fixed my problem. Thanks!

**Comment by tschaub** [comment]
Fix released in `mock-fs@4.2`.  Thanks @not-an-aardvark.
